version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: nest_crashcourse_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    networks:
      - nestcrashcourse
networks:
  nestcrashcourse:
